In [1]:
import pandas as pd
import os

mimic_path = "/hpc/home/yy450/link_kamaleswaranlab/mimic_iv/builtdata/csv_exports"
output_path = "/hpc/home/yy450/link_kamaleswaranlab/mimic_iv/mimic_flat_files"

os.makedirs(output_path, exist_ok=True)

In [2]:
micro_df = pd.read_csv(os.path.join(mimic_path, "hosp_microbiologyevents.csv"))
micro_df.head()

/tmp/ipykernel_256673/1862850426.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  micro_df = pd.read_csv(os.path.join(mimic_path, "hosp_microbiologyevents.csv"))

,microevent_id,subject_id,hadm_id,micro_specimen_id,order_provider_id,chartdate,charttime,spec_itemid,spec_type_desc,test_seq,...,org_name,isolate_num,quantity,ab_itemid,ab_name,dilution_text,dilution_comparison,dilution_value,interpretation,comments
0,3853645,19669037,NaN,5428277,P31BOX,2145-04-23 00:00:00,2145-04-23 14:14:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90015.0,VANCOMYCIN,1,=,1.00,S,NaN
1,3853646,19669037,NaN,5428277,P31BOX,2145-04-23 00:00:00,2145-04-23 14:14:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90016.0,OXACILLIN,=>4,=>,4.00,R,NaN
2,3853647,19669037,NaN,5428277,P31BOX,2145-04-23 00:00:00,2145-04-23 14:14:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90025.0,LEVOFLOXACIN,0.25,=,0.25,S,NaN
3,3853648,19669037,NaN,5428277,P31BOX,2145-04-23 00:00:00,2145-04-23 14:14:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90027.0,RIFAMPIN,<=0.5,<=,0.50,S,NaN
4,3853649,19669037,NaN,1839053,NaN,2150-04-06 00:00:00,2150-04-06 23:40:00,70079,URINE,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"< 10,000 CFU/mL."

In [3]:
cultures_df = micro_df.rename(columns={
    "subject_id": "pat_id",
    "hadm_id": "csn",
    "charttime": "specimen_collect_time",
    "chartdate": "order_time",
    "storetime": "lab_result_time",
    "test_itemid": "proc_code",
    "test_name": "proc_desc",
    "spec_itemid": "component_id",
    "spec_type_desc": "component"
})

cultures_df["loinc_code"] = "NOT AVAILABLE"

cultures_df["result_status"] = "Not Recorded"

In [4]:
final_cols = [
    "csn",
    "pat_id",
    "specimen_collect_time",
    "order_time",
    "lab_result_time",
    "result_status",
    "proc_code",
    "proc_desc",
    "component_id",
    "component",
    "loinc_code",
    "org_name",
    "ab_name",
]

cultures_final = cultures_df[final_cols]
cultures_final.head(5)

,csn,pat_id,specimen_collect_time,order_time,lab_result_time,result_status,proc_code,proc_desc,component_id,component,loinc_code,org_name,ab_name
0,NaN,19669037,2145-04-23 14:14:00,2145-04-23 00:00:00,2145-04-26 11:45:00,Not Recorded,90046,WOUND CULTURE,70070,SWAB,NOT AVAILABLE,STAPH AUREUS COAG +,VANCOMYCIN
1,NaN,19669037,2145-04-23 14:14:00,2145-04-23 00:00:00,2145-04-26 11:45:00,Not Recorded,90046,WOUND CULTURE,70070,SWAB,NOT AVAILABLE,STAPH AUREUS COAG +,OXACILLIN
2,NaN,19669037,2145-04-23 14:14:00,2145-04-23 00:00:00,2145-04-26 11:45:00,Not Recorded,90046,WOUND CULTURE,70070,SWAB,NOT AVAILABLE,STAPH AUREUS COAG +,LEVOFLOXACIN
3,NaN,19669037,2145-04-23 14:14:00,2145-04-23 00:00:00,2145-04-26 11:45:00,Not Recorded,90046,WOUND CULTURE,70070,SWAB,NOT AVAILABLE,STAPH AUREUS COAG +,RIFAMPIN
4,NaN,19669037,2150-04-06 23:40:00,2150-04-06 00:00:00,2150-04-08 08:24:00,Not Recorded,90039,URINE CULTURE,70079,URINE,NOT AVAILABLE,NaN,NaN

In [5]:
output_file = os.path.join(output_path, "CULTURES.csv")
cultures_final.to_csv(output_file, index=False)

print(f"✅ CULTURES file created: {output_file}")

✅ CULTURES file created: /hpc/home/yy450/link_kamaleswaranlab/mimic_iv/mimic_flat_files/CULTURES.csv